# Generated by Django 5.0.5 on 2024-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_jude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('secondName', models.CharField(max_length=60)),
                ('middleName', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('registrationNo', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('course', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
            ],
        ),
    ]
