# Generated by Django 5.0.5 on 2024-06-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_jude', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('registrationNo', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('course', models.CharField(max_length=60)),
                ('jumuiya', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('password1', models.CharField(max_length=60)),
                ('password2', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
