# Generated by Django 5.0.5 on 2024-06-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_jude', '0003_register_delete_geeksmodel_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('password1', models.CharField(max_length=60)),
                ('password2', models.CharField(max_length=60)),
            ],
        ),
    ]
