# Generated by Django 5.0.5 on 2024-07-05 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('st_jude', '0006_activity_header_activity_headerdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='header',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='headerDescription',
        ),
    ]
